name: CyberSource REST Client Build

on:
  push:

jobs:
  build:
    runs-on: windows-2022
    name: build
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - uses: actions/checkout@v2
    - name: Add nuget package source
      run: dotnet nuget add source --username sipsorcery --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github-nofrixion "https://nuget.pkg.github.com/nofrixion/index.json"
    - name: Install dependencies
      run: dotnet restore cybersource-rest-client-netstandard\cybersource-rest-client-netstandard.sln
    - name: Build
      run: dotnet build cybersource-rest-auth-netstandard\cybersource-rest-client-netstandard.sln -c Release --no-restore

